name: Setup and check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x  
      - run: make setup
      - run: make lint
      - run: make test